-- SELECT * FROM STUDENTS_GRADES

-- SELECT FULL_NAME FROM STUDENTS_GRADES

-- SELECT AVERAGE_SCORE FROM STUDENTS_GRADES

-- SELECT FULL_NAME FROM STUDENTS_GRADES WHERE AVERAGE_SCORE > 5

-- SELECT DISTINCT COUNTRY FROM STUDENTS_GRADES

-- SELECT DISTINCT CITY FROM STUDENTS_GRADES

-- SELECT DISTINCT GROUP_NAME FROM STUDENTS_GRADES

SELECT DISTINCT MINIMUM_GRADE FROM STUDENTS_GRADES
